project:
  type: website
  output-dir: docs


website:
  title: "Matt Babb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts-listing-page.qmd
      
      

format:
  html:
    theme:
      light: pulse
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full


editor: visual

